[theme]
primaryColor             = "#0b6e69"
backgroundColor          = "#f4efe4"
secondaryBackgroundColor = "#fbf7ef"
textColor                = "#17313e"
font                     = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true
